name: Azion Framework adapter publish test

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:

    runs-on: ubuntu-latest
    name: setup verdaccio
    services:
      verdaccio:
        image: verdaccio/verdaccio:5
        ports:
          - 4873:4873
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build
      run: npm run build
    - name: login
      run: npx npm-cli-login -u test -p 1234 -e test@domain.test -r http://localhost:4873
    - name: publish
      run: npm publish --registry http://localhost:4873
    - name: check
      run: npm info azion-framework-adapter --json --registry http://localhost:4873
    - name: install global
      run: npm install -g azion-framework-adapter --registry http://localhost:4873
